const body = document.body;
const menuButton = document.querySelector('.menu-button');
const navLinks = document.querySelectorAll('.nav a');
const year = new Date().getFullYear();
const filterButtons = document.querySelectorAll('.filter-btn');
const catalogCards = document.querySelectorAll('.catalog-card');
const langButtons = document.querySelectorAll('[data-lang]');

const translations = {
  ru: {
    'brand.role': 'хирург',
    'nav.home': 'Главная',
    'nav.services': 'Услуги',
    'nav.about': 'О враче',
    'nav.book': 'Запись',
    'common.book': 'Записаться',
    'common.viewServices': 'Смотреть услуги',
    'common.city': 'Ереван',
    'common.byAppointment': 'по записи',
    'common.whatIncluded': 'Что входит',
    'common.whatToBring': 'Что взять',
    'common.atVisit': 'На приеме',
    'common.more': 'Подробнее',
    'doctor.name': 'Доктор Виктория [Фамилия]',
    'home.hero.label': 'Хирург · Онкохирург · Пластическая хирургия',
    'home.hero.title': 'Понятная хирургическая консультация',
    'home.hero.text': 'Разбор ситуации, показаний к операции и безопасного плана лечения — без лишней тревоги.',
    'home.hero.note': 'консультации и хирургическое лечение',
    'home.directions.label': 'Направления',
    'home.directions.title': 'С чем можно обратиться',
    'home.process.label': 'Прием',
    'home.process.title': 'Коротко и по делу',
    'home.catalog.label': 'Каталог',
    'home.catalog.title': 'Полный список услуг — отдельно',
    'home.catalog.text': 'Главная остается легкой, а полный перечень консультаций и операций открыт на отдельной странице.',
    'home.catalog.button': 'Открыть услуги',
    'home.faq.label': 'Вопросы',
    'home.faq.title': 'Перед консультацией',
    'step.book': 'Запись',
    'step.exam': 'Осмотр',
    'step.plan': 'План',
    'step.follow': 'Контроль',
    'service.general.title': 'Общая хирургия',
    'service.general.short': 'Плановые консультации, хирургические жалобы и наблюдение после операции.',
    'service.general.more': 'Прием, осмотр, разбор обследований и план дальнейших действий.',
    'service.oncology.title': 'Хирургическая онкология',
    'service.oncology.short': 'Второе мнение, оценка обследований и обсуждение тактики лечения.',
    'service.oncology.more': 'Заключения, анализы, снимки и предложенный ранее план лечения.',
    'service.plastic.title': 'Пластическая хирургия',
    'service.plastic.short': 'Консультация, реалистичные ожидания, подготовка и восстановление.',
    'service.plastic.more': 'Разбор запроса, медицинских ограничений и возможного плана коррекции.',
    'faq.tests.q': 'Нужно ли приходить с анализами?',
    'faq.tests.a': 'Если обследования уже есть, лучше взять их с собой. Если нет — врач подскажет, что действительно нужно.',
    'faq.second.q': 'Можно ли получить второе мнение?',
    'faq.second.a': 'Да, можно прийти с диагнозом, заключениями и предложенным планом лечения.',
    'contact.label': 'Запись',
    'contact.title': 'Записаться на консультацию',
    'contact.text': 'Позже добавим реальные контакты, адрес клиники и расписание приема.',
    'contact.call': 'Позвонить',
    'services.hero.label': 'Каталог',
    'services.hero.title': 'Услуги и направления',
    'services.hero.text': 'Здесь будет полный перечень консультаций и операций. Сейчас — аккуратный каркас для будущего заполнения.',
    'filter.all': 'Все',
    'filter.general': 'Общая',
    'filter.oncology': 'Онко',
    'filter.plastic': 'Пластика',
    'services.general.1.title': 'Первичный прием хирурга',
    'services.general.1.text': 'Осмотр, разбор жалоб и понятный план дальнейших действий.',
    'services.general.1.more': 'Документы, обследования и рекомендации после консультации.',
    'services.general.2.title': 'Послеоперационный контроль',
    'services.general.2.text': 'Проверка восстановления, перевязки и рекомендации.',
    'services.general.2.more': 'Контрольные визиты и оценка динамики после вмешательства.',
    'services.general.3.title': 'Образования кожи и тканей',
    'services.general.3.text': 'Оценка необходимости диагностики, наблюдения или удаления.',
    'services.general.3.more': 'Точный список процедур уточним после данных врача.',
    'services.oncology.1.title': 'Второе мнение',
    'services.oncology.1.text': 'Разбор диагноза, обследований и предложенного плана.',
    'services.oncology.1.more': 'Лучше взять заключения, анализы и снимки.',
    'services.oncology.2.title': 'План хирургического лечения',
    'services.oncology.2.text': 'Обсуждение показаний, подготовки, рисков и наблюдения.',
    'services.oncology.2.more': 'Формулировки уточним под реальные зоны специализации.',
    'services.oncology.3.title': 'Маршрут пациента',
    'services.oncology.3.text': 'Понятный следующий шаг после консультации.',
    'services.oncology.3.more': 'Дополнительные обследования, консультации или подготовка к операции.',
    'services.plastic.1.title': 'Первичная консультация',
    'services.plastic.1.text': 'Запрос, ожидания, ограничения и безопасность.',
    'services.plastic.1.more': 'Оценка анатомических особенностей и противопоказаний.',
    'services.plastic.2.title': 'Подготовка к операции',
    'services.plastic.2.text': 'Обследования, сроки и реалистичный план.',
    'services.plastic.2.more': 'Без обещаний идеального результата, только после очного приема.',
    'services.plastic.3.title': 'Восстановление',
    'services.plastic.3.text': 'Ограничения, контрольные визиты и рекомендации.',
    'services.plastic.3.more': 'Сроки зависят от типа вмешательства.',
    'about.hero.label': 'О враче',
    'about.hero.text': 'Профиль врача: опыт, подход к пациентам, документы и материалы для доверия.',
    'about.approach.label': 'Подход',
    'about.approach.title': 'Спокойно, понятно, по показаниям',
    'about.approach.text': 'Позже здесь будет короткий личный текст: образование, опыт, клиники и профессиональные принципы.',
    'about.docs.label': 'Документы',
    'about.docs.title': 'Образование и сертификаты',
    'about.docs.1.title': 'Медицинское образование',
    'about.docs.1.text': 'Диплом и базовая информация.',
    'about.docs.2.title': 'Общая хирургия',
    'about.docs.2.text': 'Сертификаты и квалификация.',
    'about.docs.3.title': 'Пластическая хирургия',
    'about.docs.3.text': 'Экзамен и документы.',
    'about.docs.4.title': 'Дополнительное обучение',
    'about.docs.4.text': 'Курсы и конференции.',
    'about.materials.label': 'Материалы',
    'about.materials.title': 'Кейсы, отзывы, результаты',
    'about.materials.text': 'Только обезличенные случаи и фото с разрешением пациента.',
    'about.case.1.title': 'Карточка результата',
    'about.case.1.text': 'Фото и короткое описание без лишних деталей.',
    'about.case.2.title': 'Клинический случай',
    'about.case.2.text': 'Задача, тактика и наблюдение.',
    'about.case.3.title': 'Отзывы',
    'about.case.3.text': 'Короткие отзывы с разрешением на публикацию.',
    'footer.disclaimer': `© ${year} Dr. Viktoria. Информация на сайте не заменяет очную консультацию врача.`,
    'footer.top': 'Наверх ↑'
  },
  en: {
    'brand.role': 'surgeon',
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.book': 'Book',
    'common.book': 'Book a visit',
    'common.viewServices': 'View services',
    'common.city': 'Yerevan',
    'common.byAppointment': 'by appointment',
    'common.whatIncluded': 'What is included',
    'common.whatToBring': 'What to bring',
    'common.atVisit': 'At the visit',
    'common.more': 'More details',
    'doctor.name': 'Dr. Viktoria [Last name]',
    'home.hero.label': 'Surgeon · Oncologic surgery · Plastic surgery',
    'home.hero.title': 'Clear surgical consultation',
    'home.hero.text': 'A calm explanation of the condition, surgery indications, and a safe treatment plan.',
    'home.hero.note': 'consultations and surgical treatment',
    'home.directions.label': 'Directions',
    'home.directions.title': 'Reasons to consult',
    'home.process.label': 'Visit',
    'home.process.title': 'Short and clear',
    'home.catalog.label': 'Catalog',
    'home.catalog.title': 'Full service list on a separate page',
    'home.catalog.text': 'The home page stays light, while the full list of consultations and procedures is available separately.',
    'home.catalog.button': 'Open services',
    'home.faq.label': 'Questions',
    'home.faq.title': 'Before the consultation',
    'step.book': 'Booking',
    'step.exam': 'Exam',
    'step.plan': 'Plan',
    'step.follow': 'Follow-up',
    'service.general.title': 'General surgery',
    'service.general.short': 'Planned consultations, common surgical complaints, and post-operative follow-up.',
    'service.general.more': 'Consultation, examination, review of tests, and next-step planning.',
    'service.oncology.title': 'Oncologic surgery',
    'service.oncology.short': 'Second opinion, review of tests, and discussion of surgical treatment strategy.',
    'service.oncology.more': 'Reports, lab tests, images, and the previously suggested treatment plan.',
    'service.plastic.title': 'Plastic surgery',
    'service.plastic.short': 'Consultation, realistic expectations, preparation, and recovery plan.',
    'service.plastic.more': 'Request review, medical limitations, and a possible correction plan.',
    'faq.tests.q': 'Should I bring test results?',
    'faq.tests.a': 'If you already have tests or imaging, bring them. If not, the doctor will explain what is actually needed.',
    'faq.second.q': 'Can I get a second opinion?',
    'faq.second.a': 'Yes, you can come with a diagnosis, reports, and a proposed treatment plan.',
    'contact.label': 'Booking',
    'contact.title': 'Book a consultation',
    'contact.text': 'Real contacts, clinic address, and schedule will be added later.',
    'contact.call': 'Call',
    'services.hero.label': 'Catalog',
    'services.hero.title': 'Services and directions',
    'services.hero.text': 'The full list of consultations and procedures will be here. For now, this is a clean structure for future content.',
    'filter.all': 'All',
    'filter.general': 'General',
    'filter.oncology': 'Onco',
    'filter.plastic': 'Plastic',
    'services.general.1.title': 'Initial surgical visit',
    'services.general.1.text': 'Examination, complaint review, and a clear next-step plan.',
    'services.general.1.more': 'Documents, tests, and recommendations after the visit.',
    'services.general.2.title': 'Post-operative follow-up',
    'services.general.2.text': 'Recovery check, dressings, and recommendations.',
    'services.general.2.more': 'Follow-up visits and recovery assessment after surgery.',
    'services.general.3.title': 'Skin and soft tissue formations',
    'services.general.3.text': 'Assessment for diagnostics, observation, or removal.',
    'services.general.3.more': 'The exact procedure list will be added after doctor input.',
    'services.oncology.1.title': 'Second opinion',
    'services.oncology.1.text': 'Review of diagnosis, tests, and proposed treatment plan.',
    'services.oncology.1.more': 'Bring reports, lab results, and images if available.',
    'services.oncology.2.title': 'Surgical treatment plan',
    'services.oncology.2.text': 'Indications, preparation, risks, and follow-up.',
    'services.oncology.2.more': 'Wording will be adjusted to the real focus areas.',
    'services.oncology.3.title': 'Patient pathway',
    'services.oncology.3.text': 'A clear next step after the consultation.',
    'services.oncology.3.more': 'Additional tests, consultations, or surgery preparation.',
    'services.plastic.1.title': 'Initial consultation',
    'services.plastic.1.text': 'Request, expectations, limitations, and safety.',
    'services.plastic.1.more': 'Assessment of anatomy and contraindications.',
    'services.plastic.2.title': 'Surgery preparation',
    'services.plastic.2.text': 'Tests, timing, and a realistic plan.',
    'services.plastic.2.more': 'No guaranteed ideal result; only after an in-person visit.',
    'services.plastic.3.title': 'Recovery',
    'services.plastic.3.text': 'Restrictions, follow-up visits, and recommendations.',
    'services.plastic.3.more': 'Timing depends on the type of procedure.',
    'about.hero.label': 'About',
    'about.hero.text': 'Doctor profile: experience, patient approach, documents, and trust materials.',
    'about.approach.label': 'Approach',
    'about.approach.title': 'Calm, clear, indication-based',
    'about.approach.text': 'A short personal text about education, experience, clinics, and professional principles will go here.',
    'about.docs.label': 'Documents',
    'about.docs.title': 'Education and certificates',
    'about.docs.1.title': 'Medical education',
    'about.docs.1.text': 'Diploma and basic information.',
    'about.docs.2.title': 'General surgery',
    'about.docs.2.text': 'Certificates and qualifications.',
    'about.docs.3.title': 'Plastic surgery',
    'about.docs.3.text': 'Exam and documents.',
    'about.docs.4.title': 'Additional training',
    'about.docs.4.text': 'Courses and conferences.',
    'about.materials.label': 'Materials',
    'about.materials.title': 'Cases, reviews, results',
    'about.materials.text': 'Only anonymized cases and photos with patient permission.',
    'about.case.1.title': 'Result card',
    'about.case.1.text': 'Photo and short description without extra details.',
    'about.case.2.title': 'Clinical case',
    'about.case.2.text': 'Task, strategy, and follow-up.',
    'about.case.3.title': 'Reviews',
    'about.case.3.text': 'Short reviews with permission to publish.',
    'footer.disclaimer': `© ${year} Dr. Viktoria. Website information does not replace an in-person medical consultation.`,
    'footer.top': 'Back to top ↑'
  },
  hy: {
    'brand.role': 'վիրաբույժ',
    'nav.home': 'Գլխավոր',
    'nav.services': 'Ծառայություններ',
    'nav.about': 'Բժշկի մասին',
    'nav.book': 'Գրանցում',
    'common.book': 'Գրանցվել',
    'common.viewServices': 'Դիտել ծառայությունները',
    'common.city': 'Երևան',
    'common.byAppointment': 'նախնական գրանցմամբ',
    'common.whatIncluded': 'Ինչ է ներառված',
    'common.whatToBring': 'Ինչ բերել',
    'common.atVisit': 'Ընդունման ժամանակ',
    'common.more': 'Մանրամասն',
    'doctor.name': 'Բժիշկ Վիկտորիա [Ազգանուն]',
    'home.hero.label': 'Վիրաբույժ · Օնկովիրաբուժություն · Պլաստիկ վիրաբուժություն',
    'home.hero.title': 'Պարզ վիրաբուժական խորհրդատվություն',
    'home.hero.text': 'Իրավիճակի, վիրահատության ցուցումների և անվտանգ բուժման պլանի հանգիստ բացատրություն։',
    'home.hero.note': 'խորհրդատվություն և վիրաբուժական բուժում',
    'home.directions.label': 'Ուղղություններ',
    'home.directions.title': 'Ինչ հարցերով դիմել',
    'home.process.label': 'Ընդունում',
    'home.process.title': 'Կարճ և հստակ',
    'home.catalog.label': 'Կատալոգ',
    'home.catalog.title': 'Ծառայությունների ամբողջ ցանկը՝ առանձին էջում',
    'home.catalog.text': 'Գլխավոր էջը մնում է թեթև, իսկ ամբողջ ցանկը բացվում է առանձին էջում։',
    'home.catalog.button': 'Բացել ծառայությունները',
    'home.faq.label': 'Հարցեր',
    'home.faq.title': 'Խորհրդատվությունից առաջ',
    'step.book': 'Գրանցում',
    'step.exam': 'Զննում',
    'step.plan': 'Պլան',
    'step.follow': 'Հսկում',
    'service.general.title': 'Ընդհանուր վիրաբուժություն',
    'service.general.short': 'Պլանային խորհրդատվություններ, վիրաբուժական գանգատներ և հետվիրահատական հսկում։',
    'service.general.more': 'Ընդունում, զննում, հետազոտությունների վերլուծություն և հաջորդ քայլերի պլան։',
    'service.oncology.title': 'Օնկովիրաբուժություն',
    'service.oncology.short': 'Երկրորդ կարծիք, հետազոտությունների գնահատում և բուժման տակտիկայի քննարկում։',
    'service.oncology.more': 'Եզրակացություններ, անալիզներ, նկարներ և առաջարկված բուժման պլան։',
    'service.plastic.title': 'Պլաստիկ վիրաբուժություն',
    'service.plastic.short': 'Խորհրդատվություն, իրատեսական սպասումներ, պատրաստում և վերականգնում։',
    'service.plastic.more': 'Ցանկության, բժշկական սահմանափակումների և հնարավոր պլանի քննարկում։',
    'faq.tests.q': 'Պետք է բերել անալիզներ՞',
    'faq.tests.a': 'Եթե հետազոտություններ արդեն կան, լավ է բերել։ Եթե ոչ՝ բժիշկը կասի, թե ինչն է պետք։',
    'faq.second.q': 'Կարելի՞ է ստանալ երկրորդ կարծիք',
    'faq.second.a': 'Այո, կարելի է գալ ախտորոշմամբ, եզրակացություններով և առաջարկված բուժման պլանով։',
    'contact.label': 'Գրանցում',
    'contact.title': 'Գրանցվել խորհրդատվության',
    'contact.text': 'Հետագայում կավելացնենք իրական կոնտակտները, կլինիկայի հասցեն և գրաֆիկը։',
    'contact.call': 'Զանգել',
    'services.hero.label': 'Կատալոգ',
    'services.hero.title': 'Ծառայություններ և ուղղություններ',
    'services.hero.text': 'Այստեղ կլինի խորհրդատվությունների և միջամտությունների ամբողջ ցանկը։ Առայժմ սա լրացման համար մաքուր կառուցվածք է։',
    'filter.all': 'Բոլորը',
    'filter.general': 'Ընդհանուր',
    'filter.oncology': 'Օնկո',
    'filter.plastic': 'Պլաստիկ',
    'services.general.1.title': 'Վիրաբույժի առաջնային ընդունում',
    'services.general.1.text': 'Զննում, գանգատների քննարկում և հաջորդ քայլերի հստակ պլան։',
    'services.general.1.more': 'Փաստաթղթեր, հետազոտություններ և խորհրդատվությունից հետո առաջարկություններ։',
    'services.general.2.title': 'Հետվիրահատական հսկում',
    'services.general.2.text': 'Վերականգնման ստուգում, վիրակապում և առաջարկություններ։',
    'services.general.2.more': 'Հսկողական այցեր և վերականգնման գնահատում։',
    'services.general.3.title': 'Մաշկի և հյուսվածքների գոյացություններ',
    'services.general.3.text': 'Գնահատում՝ ախտորոշման, հսկման կամ հեռացման համար։',
    'services.general.3.more': 'Ճշգրիտ ցանկը կավելացվի բժշկի տվյալներից հետո։',
    'services.oncology.1.title': 'Երկրորդ կարծիք',
    'services.oncology.1.text': 'Ախտորոշման, հետազոտությունների և առաջարկված պլանի վերլուծություն։',
    'services.oncology.1.more': 'Լավ է բերել եզրակացություններ, անալիզներ և նկարներ։',
    'services.oncology.2.title': 'Վիրաբուժական բուժման պլան',
    'services.oncology.2.text': 'Ցուցումներ, պատրաստում, ռիսկեր և հետագա հսկում։',
    'services.oncology.2.more': 'Ձևակերպումները կհարմարեցնենք իրական մասնագիտացմանը։',
    'services.oncology.3.title': 'Պացիենտի ուղի',
    'services.oncology.3.text': 'Խորհրդատվությունից հետո հստակ հաջորդ քայլ։',
    'services.oncology.3.more': 'Լրացուցիչ հետազոտություններ, խորհրդատվություններ կամ վիրահատության պատրաստում։',
    'services.plastic.1.title': 'Առաջնային խորհրդատվություն',
    'services.plastic.1.text': 'Ցանկություն, սպասումներ, սահմանափակումներ և անվտանգություն։',
    'services.plastic.1.more': 'Անատոմիական առանձնահատկությունների և հակացուցումների գնահատում։',
    'services.plastic.2.title': 'Վիրահատության պատրաստում',
    'services.plastic.2.text': 'Հետազոտություններ, ժամկետներ և իրատեսական պլան։',
    'services.plastic.2.more': 'Առանց իդեալական արդյունքի խոստումների, միայն անձնական ընդունումից հետո։',
    'services.plastic.3.title': 'Վերականգնում',
    'services.plastic.3.text': 'Սահմանափակումներ, հսկողական այցեր և առաջարկություններ։',
    'services.plastic.3.more': 'Ժամկետները կախված են միջամտության տեսակից։',
    'about.hero.label': 'Բժշկի մասին',
    'about.hero.text': 'Բժշկի պրոֆիլ՝ փորձ, մոտեցում, փաստաթղթեր և վստահության նյութեր։',
    'about.approach.label': 'Մոտեցում',
    'about.approach.title': 'Հանգիստ, պարզ, ցուցումներով',
    'about.approach.text': 'Այստեղ կլինի կարճ անձնական տեքստ՝ կրթության, փորձի, կլինիկաների և սկզբունքների մասին։',
    'about.docs.label': 'Փաստաթղթեր',
    'about.docs.title': 'Կրթություն և սերտիֆիկատներ',
    'about.docs.1.title': 'Բժշկական կրթություն',
    'about.docs.1.text': 'Դիպլոմ և հիմնական տեղեկություն։',
    'about.docs.2.title': 'Ընդհանուր վիրաբուժություն',
    'about.docs.2.text': 'Սերտիֆիկատներ և որակավորում։',
    'about.docs.3.title': 'Պլաստիկ վիրաբուժություն',
    'about.docs.3.text': 'Քննություն և փաստաթղթեր։',
    'about.docs.4.title': 'Լրացուցիչ ուսուցում',
    'about.docs.4.text': 'Դասընթացներ և կոնֆերանսներ։',
    'about.materials.label': 'Նյութեր',
    'about.materials.title': 'Դեպքեր, կարծիքներ, արդյունքներ',
    'about.materials.text': 'Միայն անանուն դեպքեր և լուսանկարներ՝ պացիենտի թույլտվությամբ։',
    'about.case.1.title': 'Արդյունքի քարտ',
    'about.case.1.text': 'Լուսանկար և կարճ նկարագրություն՝ առանց ավելորդ մանրամասների։',
    'about.case.2.title': 'Կլինիկական դեպք',
    'about.case.2.text': 'Խնդիր, տակտիկա և հսկում։',
    'about.case.3.title': 'Կարծիքներ',
    'about.case.3.text': 'Կարճ կարծիքներ՝ հրապարակման թույլտվությամբ։',
    'footer.disclaimer': `© ${year} Dr. Viktoria. Կայքի տեղեկատվությունը չի փոխարինում բժշկի անձնական խորհրդատվությանը։`,
    'footer.top': 'Վերև ↑'
  }
};

function applyLanguage(lang) {
  const dictionary = translations[lang] || translations.ru;
  document.documentElement.lang = lang;
  localStorage.setItem('siteLanguage', lang);

  document.querySelectorAll('[data-i18n]').forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[key]) node.textContent = dictionary[key];
  });

  langButtons.forEach((button) => {
    button.classList.toggle('active', button.dataset.lang === lang);
  });
}

if (menuButton) {
  menuButton.addEventListener('click', () => {
    const isOpen = body.classList.toggle('menu-open');
    menuButton.setAttribute('aria-expanded', String(isOpen));
  });
}

navLinks.forEach((link) => {
  const currentPage = window.location.pathname.split('/').pop() || 'index.html';
  const linkPage = link.getAttribute('href')?.split('#')[0];

  if (linkPage === currentPage && !link.getAttribute('href')?.includes('#')) {
    link.classList.add('active');
  }

  link.addEventListener('click', () => {
    body.classList.remove('menu-open');
    menuButton?.setAttribute('aria-expanded', 'false');
  });
});

function setFilter(filter) {
  filterButtons.forEach((button) => {
    button.classList.toggle('active', button.dataset.filter === filter);
  });

  catalogCards.forEach((card) => {
    const visible = filter === 'all' || card.dataset.category === filter;
    card.classList.toggle('is-hidden', !visible);
  });
}

filterButtons.forEach((button) => {
  button.addEventListener('click', () => setFilter(button.dataset.filter || 'all'));
});

langButtons.forEach((button) => {
  button.addEventListener('click', () => applyLanguage(button.dataset.lang || 'ru'));
});

const hash = window.location.hash.replace('#', '');
if (['general', 'oncology', 'plastic'].includes(hash)) {
  setFilter(hash);
}

applyLanguage(localStorage.getItem('siteLanguage') || 'ru');
